# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title:
  en: Antonio Ortega
  es: Antonio Ortega
  dk: Antonio Ortega
email: rnq313@alumni.ku.dk
description: #> # this means to ignore newlines until "baseurl:"
  en: Welcome to Antonio Ortega's personal website! Here you can explore his portfolio and his profile.
  es: Bienvenido a la página personal de Antonio Ortega. Aquí puedes explorar sus proyectos y su perfil.
  dk : 
index:
  en: index.html
  es: pages/index/es.html
  dk: pages/index/dk.html

baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site
twitter_username: antortjim
github_username:  antortjim

# Build settings
markdown: kramdown
theme: minima


array: []

gems: ["youtube"]
